name: Create build check
on:
  push:
    tags:
      - '15.0**'

jobs:
  create-build-check-issue:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions: write-all
    if: contains('["SlackBuildsOrg/slackbuilds"]', github.repository)
    steps:
      - name: Check out repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          show-progress: false

      - name: Create or update release issue
        id: create-or-update-issue
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6.0.0
        with:
          title: '${{ github.ref_name }}: Build check'
          content-filepath: .github/BUILD_CHECK_ISSUE.md


